env: local
token: TEST123
mongo:
  uri: mongodb://username:password@localhost:2717/test?authSource=admin&readPreference=primaryPreferred&maxIdleTimeMS=120000&maxPoolSize=100&socketTimeoutMS=5000
  database: test
  collection: 
    orderapproval: Order_Approval_Pending_Col
    dqbatch: BATCH_EVENT_STREAM_CONFIG
rabbitmq:
  scheme: amqps
  username:
  password:
  hostname: 
  port: 8080
  vhost: rmq_test